name: CI devops 2023 - build-and-push-docker-image
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: [ CI devops 2023 - test backend ]
    types:
      - completed


  pull_request:

jobs:
  build-and-push-docker-image:
    needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}


      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./project
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_USERNAME}}/tp-app:1.0.2
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./db
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/tp-db:1.0.2
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}



      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./project/apache
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/tp-httpd:1.0.2
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}




